# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Make Gradle Executable
      run: chmod +x gradlew 
    
    - name: Create build
      run: ./gradlew clean assembleDebug  
      
    - name: Upload APK
      uses: actions/upload-artifact@v2.2.3
      with:
        name: app
        path: ./app/build/outputs/apk/debug/app-debug.apk  
        
    - name: Build Release AAB      
      run: ./gradlew bundleRelease

    - name: Sign AAB              
      uses: r0adkll/sign-android-release@v1
      with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}  
          
    - uses: actions/upload-artifact@master
      with:
          name: release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          
      
    - uses: actions/upload-artifact@master
      with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt  
     
