# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Make Gradle Executable
      run: chmod +x gradlew 

    - name: Generate Release .aab
      run: ./gradlew bundleRelease
     
    - name: Sign .aab
      uses: r0adkll/sign-android-release@v1
       
      id: sign_app_bundle
      with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
     
    - name: Upload aab
    - uses: actions/upload-artifact@v2.2.3
      with:
       name: release.aab
       path: .app/build/outputs/bundle/release/release.aab
    
    - name: Generate Release APK
      run: ./gradlew assembleRelease
     
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
       
      id: sign_app_apk
      with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
   
    - name: Upload apk
    - uses: actions/upload-artifact@v2.2.3
      with:
       name: release.apk
       path: .app/build/outputs/apk/release/release.apk
     
