# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Make Gradle Executable
      run: chmod +x gradlew 
    
    - name: Create build
      run: ./gradlew clean assembleDebug  
      
    - name: Upload APK
      uses: actions/upload-artifact@v2.2.3
      with:
        name: app
        path: ./app/build/outputs/apk/debug/app-debug.apk    
      
      
