name: testing

on:
  push:
    branches: [ Test ]
  pull_request:
    branches: [ Test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: create directory
      run : |
       mkdir /home/runner/work/ravi   
       echo $RUNNER_TEMP
       
    - name: Get secret from base64
      env:
       KEYSTORE_BASE64: ${{ secrets.SIGNING_KEY }}
      run: |
       echo import certificate from secrets and regenerate the file
       echo $KEYSTORE_BASE64 | base64 -d > /home/runner/work/ravi/my_file.keystore   

